INDICATORS = {
    "monetary_base": {
        "name_jp": "マネタリーベース",
        "name_en": "Monetary Base",
        "db": "MD01",
        "codes": ["MABS1AN11"],
        "frequency": "M",
        "unit": "億円",
    },
    "money_stock_m2": {
        "name_jp": "マネーストック (M2)",
        "name_en": "Money Stock (M2)",
        "db": "MD02",
        "codes": ["MAM1NAM2M2MO"],
        "frequency": "M",
        "unit": "億円",
    },
    "money_stock_m3": {
        "name_jp": "マネーストック (M3)",
        "name_en": "Money Stock (M3)",
        "db": "MD02",
        "codes": ["MAM1NAM3M3MO"],
        "frequency": "M",
        "unit": "億円",
    },
    "cgpi": {
        "name_jp": "企業物価指数 (CGPI)",
        "name_en": "Corporate Goods Price Index",
        "db": "PR01",
        "codes": ["PRCG20_2200000000"],
        "frequency": "M",
        "unit": "2020=100",
    },
    "exchange_rate_usd_jpy": {
        "name_jp": "為替レート (USD/JPY)",
        "name_en": "Exchange Rate (USD/JPY)",
        "db": "FM08",
        "codes": ["FXERM07"],
        "frequency": "M",
        "unit": "円/ドル",
    },
    "call_rate": {
        "name_jp": "コールレート (無担保翌日物)",
        "name_en": "Call Rate (Uncollateralized Overnight)",
        "db": "FM02",
        "codes": ["STRACLUCON"],
        "frequency": "M",
        "unit": "%",
    },
    "basic_discount_rate": {
        "name_jp": "基準割引率・基準貸付利率",
        "name_en": "Basic Discount / Loan Rate",
        "db": "IR01",
        "codes": ["MADR1M"],
        "frequency": "M",
        "unit": "%",
    },
    "tankan_di": {
        "name_jp": "短観 業況判断DI (大企業製造業)",
        "name_en": "Tankan DI (Large Manufacturing)",
        "db": "CO",
        "codes": [
            "TK99F1000601GCQ01000",
            "TK99F2000601GCQ01000",
        ],
        "frequency": "Q",
        "unit": "%ポイント",
    },
    "balance_of_payments": {
        "name_jp": "国際収支 (経常収支)",
        "name_en": "Balance of Payments (Current Account)",
        "db": "BP01",
        "codes": ["BPBP6JYNCB"],
        "frequency": "M",
        "unit": "億円",
    },
}
